---
- hosts: all
  tasks:
  - name: Build Docker image
    docker_image:
      name: my-app:latest
      build:
        path: ./
        dockerfile: Dockerfile

  - name: Run Docker container
    docker_container:
      name: my-app
      image: my-app:latest
      ports:
        - "8080:8080"